In [1]:
import pandas as pd
var=pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,5]})
var

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [2]:
var.insert(1,"python_1",var["A"])
var

   A  python_1  B
0  1         1  9
1  2         2  8
2  3         3  7
3  4         4  6
4  5         5  5

In [8]:
var.insert(1,"python_2",[11,12,23,34,15])
var

   A  python_2  python_1  B
0  1        11         1  9
1  2        12         2  8
2  3        23         3  7
3  4        34         4  6
4  5        15         5  5